First `README.md` file skeleton
KiraCore/ryokai pull request #10
Opened 2024-03-13 17:10 UTC by andrsj

2024-03-13 17:30 UTC, MrLutik requested changes

2024-03-13 17:30 UTC, MrLutik commented on README.md
> +  - [Roadmap](#roadmap)
Nope

2024-03-13 17:30 UTC, MrLutik commented on README.md
> +> `RYOKAI` supports network operations by automating on-chain and off-chain upgrades, scaling, RollApp deployment, simplifying consensus nodes' management tasks, and enhancing the network's efficienc
Add the vault integration paragraph with the link.

2024-03-13 17:30 UTC, MrLutik commented on README.md
> +`Ryokai` is the **new infrastructure manager tool** from [KiraCore team](https://github.com/KiraCore/).
** new orchestrator tool***

2024-03-13 17:40 UTC, andrsj commented on README.md
> +  - [Roadmap](#roadmap)
@MrLutik shall we not have a roadmap?

2024-03-13 17:50 UTC, MrLutik approved these changes

2024-03-14 09:25 UTC, PeepoFrog approved these changes

2024-03-14 09:28 UTC, merged