Feature/os utils transfering
KiraCore/ryokai pull request #3
Opened 2024-02-25 12:19 UTC by PeepoFrog

New PR after fixes

2024-02-25 12:26 UTC, MrLutik requested changes

2024-02-25 12:26 UTC, MrLutik commented on pkg/ryokaicommon/utils/os/os_test.go
> +func TestCheckIfPortIsValid(t *testing.T) {
TestCheckIfPortIsValid ->  TestValidatePort

2024-02-25 12:26 UTC, MrLutik commented on pkg/ryokaicommon/utils/os/os_test.go
> +
I would expect also TestValidateIP.

2024-02-25 13:11 UTC, MrLutik approved these changes
Nicely done

2024-02-25 13:11 UTC, merged

2024-02-26 13:11 UTC, andrsj commented on pkg/ryokaicommon/utils/os/os.go
> +func FileExist(path string) bool {
`PathExists` much better describes the function

2024-02-26 13:11 UTC, andrsj commented on pkg/ryokaicommon/utils/os/os.go
> +		return []byte{}, fmt.Errorf("error when spiting cmd to array of args, err: %w", err)
`return nil, fmt.Errorf(...)` looks MUCH better

2024-02-26 13:11 UTC, andrsj commented on pkg/ryokaicommon/utils/os/os.go
> +	return !(port < 0 || port > 65535)
`return port >= 0 && port <= 65535` easier to read